load data
 INFILE '/tpch-dbgen/supplier.tbl'
 INTO TABLE SUPPLIER
 APPEND
 FIELDS TERMINATED BY '|'
 ( S_SUPPKEY,
  S_NAME,
  S_ADDRESS,
  S_NATIONKEY,
  S_PHONE,
  S_ACCTBAL "TO_NUMBER(:S_ACCTBAL, '9999999999D999999', 'NLS_NUMERIC_CHARACTERS=''. ''')",
  S_COMMENT)
