load data
INFILE '/tpch-dbgen/customer.tbl'
INTO TABLE CUSTOMER
APPEND
FIELDS TERMINATED BY '|'
(C_CUSTKEY,
 C_NAME,
 C_ADDRESS,
 C_NATIONKEY,
 C_PHONE,
 C_ACCTBAL "TO_NUMBER(:C_ACCTBAL, '9999999999D999999', 'NLS_NUMERIC_CHARACTERS=''. ''')",
 C_MKTSEGMENT,
 C_COMMENT)
