load data
INFILE '/tpch-dbgen/orders.tbl'
INTO TABLE ORDERS
APPEND
FIELDS TERMINATED BY '|'
(O_ORDERKEY,
 O_CUSTKEY,
 O_ORDERSTATUS,
 O_TOTALPRICE "TO_NUMBER(:O_TOTALPRICE, '9999999999D999999', 'NLS_NUMERIC_CHARACTERS=''. ''')",
 O_ORDERDATE DATE 'YYYY-MM-DD',
 O_ORDERPRIORITY,
 O_CLERK,
 O_SHIPPRIORITY,
 O_COMMENT)
