load data
INFILE '/tpch-dbgen/partsupp.tbl'
INTO TABLE PARTSUPP
APPEND
FIELDS TERMINATED BY '|'
( PS_PARTKEY,
 PS_SUPPKEY,
 PS_AVAILQTY,
 PS_SUPPLYCOST "TO_NUMBER(:PS_SUPPLYCOST, '9999999999D999999', 'NLS_NUMERIC_CHARACTERS=''. ''')",
 PS_COMMENT)
