load data
INFILE '/tpch-dbgen/part.tbl'
INTO TABLE PART
APPEND
FIELDS TERMINATED BY '|'
( P_PARTKEY,
 P_NAME,
 P_MFGR,
 P_BRAND,
 P_TYPE,
 P_SIZE,
 P_CONTAINER,
 P_RETAILPRICE "TO_NUMBER(:P_RETAILPRICE, '9999999999D999999', 'NLS_NUMERIC_CHARACTERS=''. ''')",
 P_COMMENT)
